# Generated by Django 4.2.5 on 2025-02-06 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def add_basic_external_credentials(apps, schema_editor):

    provider_table = apps.get_model('core', 'Provider')

    provider_coin_market = provider_table.objects.create(
        code="COIN_MARKET_CAP",
        name="Coin Market Cap",
    )

    provider_blockchair = provider_table.objects.create(
        code="BLOCKCHAIR",
        name="Blockchair",
    )

    credentials_table = apps.get_model('core', 'ExternalCredentials')

    credentials_table.objects.create(
        code="sandbox_coinmarketcap",
        api_key="b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c",
        test_mode=True,
        base_url="https://sandbox-api.coinmarketcap.com",
        provider=provider_coin_market,
    )
    credentials_table.objects.create(
        code="prod_coinmarketcap",
        test_mode=False,
        base_url="https://pro-api.coinmarketcap.com",
        provider=provider_coin_market,
    )
    credentials_table.objects.create(
        code="sandbox_blockchair",
        test_mode=True,
        base_url="https://api.blockchair.com",
        provider=provider_blockchair,
    )
    credentials_table.objects.create(
        code="prod_blockchair",
        test_mode=False,
        base_url="https://api.blockchair.com",
        provider=provider_blockchair,
    )


def add_currencies(apps, schema_editor):

    currencies_table = apps.get_model('core', 'Currency')
    currencies_table.objects.create(
        code="BTC",
        name="Bitcoin",
    )
    currencies_table.objects.create(
        code="ETH",
        name="Ethereum",
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=28)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=28)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=128)),
                ('expired_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_credentials',
            },
        ),
        migrations.CreateModel(
            name='ExternalCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('api_key', models.CharField(blank=True, max_length=256, null=True)),
                ('access_token', models.CharField(blank=True, max_length=256, null=True)),
                ('test_mode', models.BooleanField(default=False)),
                ('base_url', models.URLField()),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.provider')),
            ],
            options={
                'db_table': 'external_credentials',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_numbers', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.provider')),
                ('external_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'block',
            },
        ),
        migrations.RunPython(add_basic_external_credentials),
        migrations.RunPython(add_currencies),
    ]
